jenkins-dind:
  container_name: jenkins-dind
  image: killercentury/jenkins-dind
  ports:
    - 9080:8080
    - 50000:50000
    - 9082:9082
    - 8000:8000
    - 1337:1337
    - 3000:3000
  privileged: true


  volumes:
    - ./JENKINS_HOME:/jenkins
  environment:
    - JENKINS_HOME:/jenkins
